<?php
////////////////////////////////////////LIKES//////////////////////////////////////////////////////////////////////
?>

<div style="text-align: center;">

<!-- Put this script tag to the <head> of your page -->
<script src="//vk.com/js/api/openapi.js?98" type="text/javascript"></script>
<script type="text/javascript">// <![CDATA[
VK.init({apiId: 3837853, onlyWidgets: true});
// ]]></script>
<!-- Put this div tag to the place, where the Like block will be -->
<div id="vk_like" style="display: inline;">&nbsp;</div>
<script type="text/javascript">// <![CDATA[
VK.Widgets.Like("vk_like", {type: "button", height: 25, pageTitle: 'Расписания МГТУ ГА', pageUrl: 'http://sd.mstuca.su/about/',
pageDescription: 'Расписания занятий Московского Государственного Технического Университета Гражданской Авиации', text: 'Интерактивное расписания занятий Московского Государственного Технического Университета Гражданской Авиации', pageImage: 'http://sd.studga.ru/css/images/mstuca_professor_150-150.png'}, 0);
// ]]></script>

<?php /*/?>
<a class="twitter-share-button" href="https://twitter.com/share?url=http://sd.studga.ru/&amp;text=Расписания%20МГТУ%20ГА&amp;lang=ru&amp;size=large&amp;dnt=true&amp;count=none">Твитнуть</a>
&amp;via=Nvd5517
<?php /*/?>

<a class="twitter-share-button" href="https://twitter.com/share?url=http://sd.studga.ru&amp;text=Расписания%20МГТУ%20ГА&amp;lang=ru&amp;size=large&amp;dnt=true">Твитнуть</a>

<script type="text/javascript">!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?
'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';
fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
</script>


<iframe style="display: inline; border: none; overflow: hidden; width: 130px; height: 25px;"
src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fsd.studga.ru&amp;width=130&amp;height=25&amp;colorscheme=light&amp;layout=button_count&amp;action=like&amp;show_faces=true&amp;send=false"
width="300" height="150" frameborder="0" scrolling="no"></iframe>


<table style="border-collapse: collapse; border: 0px solid #000000;display: inline; height: 25px;width: 250px; text-align: center;"><tr>
<td style="text-align: center;">
<a class="mrc__plugin_uber_like_button"
href="http://connect.mail.ru/share?mrc-config={'cm':'1','sz':'20','st':'2','tp':'mm','height': 25,'width': 50}&amp;width=50&amp;url=http%3A%2F%2Fsd.studga.ru&amp;title=Расписания%20МГТУ%20ГА&amp;description=Интерактивное%20расписания%20занятий%20Московского%20Государственного%20Технического%20Университета%20Гражданской%20Авиации&amp;imageurl=http%3A%2F%2Fsd.studga.ru%2Fcss%2Fimages%2Fmstuca_professor_150-150.png" target="_blank">Нравится</a></td>
</tr></table>
<script src="http://cdn.connect.mail.ru/js/loader.js" type="text/javascript" charset="UTF-8"></script>


<?php /*/ ?>
<!-- Поместите этот тег туда, где должна отображаться кнопка +1. -->
<div class="g-plusone" style="display: inline;">&nbsp;</div>
<!-- Поместите этот тег за последним тегом виджета кнопка +1. -->
<script type="text/javascript">// <![CDATA[
window.___gcfg = {lang: 'ru'};

  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
// ]]></script>
<%/*/?>

</div>
<?php
////////////////////////////////////////LIKES////END///////////////////////////////////////////////////////////////
?>
